name: Run all tests

on:
  schedule:
    # Todos los dias a las 00:00
    - cron: '0 0 * * *'
  # Cada vez que se hace un push a estas branches
  push:
    branches:
      - main
      - develop
      - feature/*

  # Cada vez que se hace un pull request que involucre las branches
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # Add other dependencies as needed
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest