name: Run all tests

on:
  schedule:
    # Todos los dias a las 00:00
    - cron: '0 0 * * *'
  # Cada vez que se hace un push a cualquier branch
  push:
    branches:
      - featurePotenciador

  # Cada vez que se hace un pull request que involucre las branches
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame

    - name: Run tests
      run: python -m unittest discover -s testing